# Generated by Django 4.2.1 on 2023-08-31 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigOficina', models.IntegerField()),
                ('nombreOficina', models.CharField(max_length=50)),
                ('liderOficina', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('identificacion', models.CharField(max_length=20)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.oficina')),
            ],
        ),
    ]
